## EXPLORATORY DATA ANALSYSIS (EDA)
# BomaMicro Finance -Credit Risk & Default Prediction engine

In [ ]:
#Importing the required libraries for exploratory data analysis (EDA)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

sns.set_style('whitegrid')
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', lambda x: '%.2f' % x)


print("libraries imported successfully")

libraries imported successfully

Loading the dataset so as we can do summary statistics of the dataset

In [14]:
#loading dataset

df = pd.read_csv('boma_loans_raw.csv')

In [15]:
# displaying the first 10 rows of the dataset

df.head(10)

,customer_id,age,region,monthly_income_tzs,loan_amount_tzs,mobile_money_tx_30d,previous_defaults,days_late_avg,is_default
0,TZ-LOAN-10000,56.0,Dar es Salaam,3.942840e+05,50000,19,2,4.578967,0
1,TZ-LOAN-10001,69.0,Mbeya,7.926097e+05,50000,29,0,1.920357,0
2,TZ-LOAN-10002,46.0,Dodoma,8.397363e+05,100000,21,0,8.925104,0
3,TZ-LOAN-10003,32.0,Dodoma,5.077465e+05,1000000,18,0,4.581535,0
4,TZ-LOAN-10004,60.0,Mwanza,4.184684e+05,250000,24,0,6.156569,0
5,TZ-LOAN-10005,25.0,Dar es Salaam,1.132856e+06,1000000,29,0,0.607592,0
6,TZ-LOAN-10006,38.0,Dar es Salaam,7.182488e+05,500000,29,0,1.545294,0
7,TZ-LOAN-10007,56.0,Dodoma,8.407903e+05,1000000,22,0,28.523328,0
8,TZ-LOAN-10008,36.0,Arusha,4.033772e+05,1000000,22,0,2.842735,1
9,TZ-LOAN-10009,40.0,Dodoma,2.842147e+05,500000,22,0,2.222578,0

In [16]:
#displaying the last 10 rows of the dataset
df.tail(10)

,customer_id,age,region,monthly_income_tzs,loan_amount_tzs,mobile_money_tx_30d,previous_defaults,days_late_avg,is_default
9990,TZ-LOAN-19990,44.0,Arusha,676808.221579,1000000,22,2,1.976920,1
9991,TZ-LOAN-19991,35.0,Mbeya,945370.953787,250000,17,0,4.664735,0
9992,TZ-LOAN-19992,41.0,Dar es Salaam,834231.741587,100000,25,0,0.060389,0
9993,TZ-LOAN-19993,54.0,Mwanza,542047.861766,50000,24,0,2.277017,0
9994,TZ-LOAN-19994,150.0,Dodoma,918755.264031,1000000,26,0,0.010265,0
9995,TZ-LOAN-19995,55.0,Arusha,677444.001793,500000,19,0,0.904363,0
9996,TZ-LOAN-19996,51.0,Dar es Salaam,618160.397716,250000,28,0,2.969682,0
9997,TZ-LOAN-19997,57.0,Mbeya,507140.251880,100000,28,0,3.829529,0
9998,TZ-LOAN-19998,64.0,Mbeya,699805.654362,1500000,23,0,0.829851,0
9999,TZ-LOAN-19999,32.0,Dar es Salaam,948938.784624,250000,23,0,6.836701,0

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          10000 non-null  str
 1   age                  10000 non-null  float64
 2   region               10000 non-null  str
 3   monthly_income_tzs   9506 non-null   float64
 4   loan_amount_tzs      10000 non-null  int64
 5   mobile_money_tx_30d  10000 non-null  int64
 6   previous_defaults    10000 non-null  int64
 7   days_late_avg        9700 non-null   float64
 8   is_default           10000 non-null  int64
dtypes: float64(3), int64(4), str(2)
memory usage: 703.3 KB

In [18]:
df.describe()

,age,monthly_income_tzs,loan_amount_tzs,mobile_money_tx_30d,previous_defaults,days_late_avg,is_default
count,10000.000000,9.506000e+03,1.000000e+04,10000.000000,10000.000000,9700.000000,10000.000000
mean,44.055500,6.415091e+05,5.728950e+05,24.948800,0.380600,4.984084,0.180000
std,16.663133,3.111646e+05,5.200568e+05,4.960972,0.743235,4.894281,0.384207
min,18.000000,-5.009967e+05,5.000000e+04,8.000000,0.000000,0.001351,0.000000
25%,31.000000,4.384204e+05,1.000000e+05,21.000000,0.000000,1.461836,0.000000
50%,43.000000,6.449638e+05,5.000000e+05,25.000000,0.000000,3.520460,0.000000
75%,57.000000,8.501983e+05,1.000000e+06,28.000000,1.000000,6.982755,0.000000
max,150.000000,1.708717e+06,1.500000e+06,44.000000,3.000000,40.392714,1.000000

In [19]:
print(f"shape: {df.shape[0]: ,} rows and {df.shape[1]: ,} columns")
print(f"Memory footprint: {df.memory_usage(deep=True).sum()/1024:.1f} KB\n")

shape:  10,000 rows and  9 columns
Memory footprint: 1701.9 KB